project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "China India Economy"
  author:
    - Varsha Appaji (vla2116)
    - Kevin Xu (UNI2)
  repo-url: https://github.com/kevinxu48/EDAVFinal_Appaji_Xu.git
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


