# Conclusion
It is clear that China and India continue to experience significant economic growth. This is not only true in the global order, as evidenced by a comparison of India and China to the US, but also on a country-level basis, where China and India both have rising per capita GDPs and demonstrate resilience in the face of shocks like COVID-19. Whether India will outpace China is still a highly salient question without expert consensus. This project, however, sheds some light. First, our analysis on population indicates that India's trajectory can be a great contributor to its growth over China. However, the positive effects of population are conditioned on whether this translates to a labor force that can compete with China's, as well as, if energy sources can keep up without counterproductive environmental effects. Additionally, we find that perhaps a macroeconomic picture of growth may mask the true economic health of each country-- for instance, our analysis indicates that people in India are currently experiencing greater purchasing power and employment than in China, which could translate into greater output and overall growth in the future. 

We also observed how growth and economic expansion can impact the environment and vice versa. The rapid growth of China and India's economies have unfortunately come at the price of high environmental pollution, which was seen through the map of emissions quantities and in how there has been no major shift away from high-emission energy sources over the years in either country. As a result, we saw that they have both experienced lower ND-GAIN scores at some point in the past 30 years relative to other major economic players (particularly in India's case). Despite this, we saw that both countries are steadily improving in their resilience to emerging environmental impacts, signifying a resilience to potential economic shock in the future as well.  

For the most part, we were lucky to be working with economic data from long-standing/reputed sources, as it reduced the challenge of wrangling the data. Still, we discovered that many datasets are difficult to transform into a form conducive to plotting, despite many attempts. For example, we attempted to plot a boxplot-time-series of the age distributions in China and India over the years, but appropriately transforming the data was beyond the memory/computational capacity of our personal systems. We also gained first hand experience in the interdisciplinary nature of a data scientist-- it is not sufficient alone to have technical/computational knowledge, some amount of domain expertise is required as well in order to understand what variables to explore, which relationships are important, whether our analysis aligns with theoretical guidelines, and more. 

We also experienced the power of exploratory data analysis in lifting pre-conceived notions. For instance, when analyzing the ND-Gain index scores, we expected China to be significantly less resilient to environmental impacts, but its ND-Gain index was actually high since 2006. Finally, we learned to responsibly communicate the results of exploratory data analysis (i.e. we do not claim to have drawn any definitive conclusions without deriving any models). For instance, we expected the GDP growth heatmap to be more conclusive, but it is difficult to determine which economy has been growing faster since 2010 because both countries have had increasing GDP growth at similar rates.

