# Introduction

Historically, China has had the largest economic growth since the late 1900's. However, there is growing speculation that India's growth may outpace China's, particularly as India's population is relatively growing faster and is increasingly younger. We decided to explore this conversation in depth. The main question we would like to propose is: how/why have the two countries' growth stories differed, and how do their historical trends set them up for the future? We would like to analyze how existing patterns of growth are changing and contextualize them among emerging international issues. We are interested in exploring this topic because firstly on a personal level, this analysis adds another layer of awareness of our respective cultural heritages. Additionally, as aspiring data scientists and technologists, knowledge of India and China's position in the global order is highly relevant. 

To capture the make up of India and China's economies we will consider a few key metrics (in addition to other nuanced measures, which will be discussed later): GDP, unemployment, inflation, consumer spending, government debt, prices, and exchange rate. First, we will examine how China and India's economies stack up against their demographic characteristics, such as population growth, the age-dependency ratio, and educational attainment. 

Next, we are interested in investigating how India and China's economies are set up in light of climate-related challenges and why they are facing these challenges. Through this, we will provide insight on how much each country's GDP depends on high-emission industries, and how this matches up to resource availability and potential international regulations. Furthermore, we will assess the vulnerabilities of each country to potential climate-related disasters, and how their respective economies measure up. In doing so, we seek to provide insight on how China and India comparatively fare in the future. In this vein, we will also analyze how technology plays a role into both countries' growth stories. We will explore this dimension both in terms of access to technology in each country, as well as technology production. Key to our ideation on the future of these economies is a qualitative contextualization of these findings. For example, as emerging technology is still a very new field, albeit extremely important to the story of economic growth, there is relatively little data available on this topic. Therefore, we can combine our quantitative findings on measures like technology production with a qualitative analysis on how each country has set its agenda for engaging in the emerging technological landscape. This will allow for a holistic picture of India and China's economic trajectories. 
